[package]
name = "linear-algebra"
version = "0.7.4"
authors = ["Ozaren <krishna.sd.2012@gmail.com>"]

[features]
sized = ["typenum"]

[dependencies]
rand = "0.4.2"
num = "*"

typenum = { version = '*', optional = true }